<a id='item312'></a>


In [ ]:
import numpy as np

<a id='question01'></a>
## Question 01




In [ ]:
#Leave the answer of question 01 here!

In [1]:
import numpy as np

six0 = np.zeros((6))
print (six0)

[0. 0. 0. 0. 0. 0.]


<a id='question02'></a>
## Question 02




In [ ]:
#Leave the answer of question 02 here!

In [2]:
M_3_5_1 = np.ones((3,5))
print(M_3_5_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<a id='question03'></a>
## Question 03




In [ ]:
#Leave the answer of question 03 here!

In [3]:
A_20_60 = np.arange(20,61,1)
print (A_20_60)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


<a id='question04'></a>
## Question 04




In [ ]:
#Leave the answer of question 04 here!

In [4]:
A_15_55 = np.arange(15,56,2)
print (A_15_55)

[15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55]


<a id='question05'></a>
## Question 05




In [ ]:
#Leave the answer of question 05 here!

In [5]:
R15 = np.random.rand(15)
print(R15)

[0.57468759 0.81844713 0.85184963 0.65759678 0.79443929 0.36905655
 0.73546522 0.59819185 0.16677861 0.59141987 0.4672427  0.61323116
 0.71996733 0.17377051 0.08216473]


<a id='question06'></a>
## Question 06




In [ ]:
#Leave the answer of question 06 here!

In [6]:
Eye_4 = np.eye(4)
print(Eye_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<a id='question07'></a>
## Question 07




In [ ]:
#Leave the answer of question 07 here!

In [7]:
Ns_3_5 = np.random.randn(3, 5)
print(Ns_3_5)

[[-0.35955124  0.3416812  -0.63247727  0.18634857  0.8448953 ]
 [ 0.41147041 -0.82157913  0.06453833  0.16960929  0.57253668]
 [ 0.7446284   1.30640971 -0.53394984 -0.58488933 -0.19055261]]


<a id='question08'></a>
## Question 08




In [ ]:
#Leave the answer of question 08 here!

In [8]:
R13 = np.linspace(0,1,13)
print(R13)

[0.         0.08333333 0.16666667 0.25       0.33333333 0.41666667
 0.5        0.58333333 0.66666667 0.75       0.83333333 0.91666667
 1.        ]


<a id='question09'></a>
## Question 09




In [ ]:
#Leave the answer of question 09 here!

In [9]:
N_m6_s4 = np.random.normal(6, 4, size=(4,6))
print(N_m6_s4)

[[ 3.02883434  7.05864799  8.11493928  4.42807988  0.84461124  8.55082532]
 [ 3.56122494  2.84238822 -2.57796495 11.75081585  4.90429669  5.36432474]
 [ 1.47179565  7.24394419 14.43359756  9.29621951  6.1054633  10.32216186]
 [ 6.36899461 12.56742063  2.29349917  2.77464806  5.31774819  1.26526183]]


In [ ]:
#Second Method

In [10]:
N_m6_s4_secondM = np.random.normal(6, 4, 24).reshape(4, 6)
print(N_m6_s4_secondM)

[[11.69541293 -1.48743739  2.16767301  5.64518831  9.05772477  6.51816604]
 [ 4.87275168  1.80730962  7.71963234  9.9497138   5.32406709  9.75769074]
 [ 4.45473924 -0.06022452 12.03453898  3.00695104  8.90047553  7.16476391]
 [ 5.33026929 -2.62129111  6.11924837  4.68286433  6.0948244   5.7809274 ]]
